language: node_js
dist: trusty
sudo: required
node_js: 11.13.0
install:
  - npm i
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
